# Kodak-24: common benchmark for every reconstruction model

This is the team's single local evaluation entry point. It uses all 24 native-resolution Kodak images and produces one CSV row per method × operating point × image. Built-in RAW RGB24 and JPEG baselines use exactly the same timing and quality code as learned models.

**Metric rules:** PSNR/SSIM are RGB `[0,1]`; LPIPS is AlexNet; CBR is complex channel uses divided by `3×H×W`; compression ratio is raw RGB24 bits divided by serialized payload bits. JPEG/RAW do not claim a CBR unless a digital PHY is explicitly supplied. No evaluation-side resizing is allowed.

## 1. Environment

Create the repository's Python 3.12 environment and install `requirements.txt` before opening this notebook. If this kernel is new, run `%pip install -e ..[benchmark,metrics]` once and restart it. LPIPS may download its pretrained AlexNet weights on first use.

In [1]:
from pathlib import Path
import getpass, math, os, random, subprocess, sys

import numpy as np
import pandas as pd
from PIL import Image
import torch

candidate = Path.cwd().resolve()
PROJECT_ROOT = candidate if (candidate / 'pyproject.toml').is_file() else candidate.parent
if not (PROJECT_ROOT / 'pyproject.toml').is_file():
    raise RuntimeError('Start Jupyter in the repository root or its Notebooks directory.')
SRC = PROJECT_ROOT / 'src'
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from Evaluation.kodak_benchmark import (
    CallableCodec, EncDecCodec, JPEGCodec, RawRGBCodec, append_rows_csv,
    benchmark_codec, dataset_files, environment_summary, make_run_id,
    summarize_rows,
)
environment_summary()

{'python': '3.13.4',
 'platform': 'Windows-11-10.0.26200-SP0',
 'torch': '2.14.0+cpu',
 'cuda': 'None',
 'device': 'CPU'}

In [2]:
# Team/run configuration. Keep one RUN_ID for one complete execution.
CONTRIBUTOR = os.getenv('KODAK_BENCHMARK_CONTRIBUTOR', getpass.getuser())
RUN_ID = os.getenv('KODAK_BENCHMARK_RUN_ID', make_run_id())
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
KODAK_DIR = PROJECT_ROOT / 'data' / 'Kodak24'
CSV_PATH = PROJECT_ROOT / 'results' / 'kodak24_benchmark.csv'
JPEG_QUALITIES = [int(value) for value in os.getenv('KODAK_JPEG_QUALITIES', '20,30,40,50,60,70,80,90').split(',')]
TIMING_REPETITIONS = int(os.getenv('KODAK_TIMING_REPETITIONS', '3'))
WARMUP_REPETITIONS = int(os.getenv('KODAK_WARMUP_REPETITIONS', '1'))
COMPUTE_LPIPS = os.getenv('KODAK_COMPUTE_LPIPS', '1') == '1'
SEED = int(os.getenv('KODAK_BENCHMARK_SEED', '42'))
REPAIRED_EXPERIMENT_ROOT = os.getenv('SEMCOM_EXPERIMENT_ROOT')
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
print({'contributor': CONTRIBUTOR, 'run_id': RUN_ID, 'device': DEVICE})

{'contributor': 'Nandini.P', 'run_id': 'repaired-kodak24-20260922', 'device': 'cpu'}

## 2. Download and audit Kodak-24

The downloader resumes valid files, downloads through `.part` files, checks the published byte count and canonical SHA-256, validates each RGB PNG header and dimension, and writes a local manifest. This notebook then decodes every image with Pillow. The dataset directory is intentionally ignored by Git.

In [3]:
subprocess.run(
    [sys.executable, str(PROJECT_ROOT / 'scripts' / 'download_kodak24.py'), '--output', str(KODAK_DIR)],
    check=True, cwd=PROJECT_ROOT,
)
KODAK_FILES = dataset_files(KODAK_DIR)
audit = []
for path in KODAK_FILES:
    with Image.open(path) as image:
        audit.append({'image_id': path.stem, 'width': image.width, 'height': image.height, 'mode': image.mode})
audit_df = pd.DataFrame(audit)
assert len(audit_df) == 24 and set(audit_df['mode']) == {'RGB'}
display(audit_df)
display(audit_df.groupby(['width', 'height']).size().rename('images').reset_index())

   image_id  width  height mode
0   kodim01    768     512  RGB
1   kodim02    768     512  RGB
2   kodim03    768     512  RGB
3   kodim04    512     768  RGB
4   kodim05    768     512  RGB
5   kodim06    768     512  RGB
6   kodim07    768     512  RGB
7   kodim08    768     512  RGB
8   kodim09    512     768  RGB
9   kodim10    512     768  RGB
10  kodim11    768     512  RGB
11  kodim12    768     512  RGB
12  kodim13    768     512  RGB
13  kodim14    768     512  RGB
14  kodim15    768     512  RGB
15  kodim16    768     512  RGB
16  kodim17    512     768  RGB
17  kodim18    512     768  RGB
18  kodim19    512     768  RGB
19  kodim20    768     512  RGB
20  kodim21    768     512  RGB
21  kodim22    768     512  RGB
22  kodim23    768     512  RGB
23  kodim24    768     512  RGB

   width  height  images
0    512     768       6
1    768     512      18

## 3. Register methods

RAW and JPEG are ready. Add each learned model either through `EncDecCodec` (preferred for repository adapters) or `CallableCodec`. Give every checkpoint/rate/SNR a distinct `operating_point` and a checkpoint hash or version string.

For continuous JSCC, report **complex channel uses**, not bytes. For an actually serialized latent, provide `payload_bits_fn`. If a number is not meaningful, leave it empty instead of inventing a conversion.

In [4]:
METHODS = [RawRGBCodec()] + [JPEGCodec(quality) for quality in JPEG_QUALITIES]
repaired_provenance = None
if REPAIRED_EXPERIMENT_ROOT:
    from Evaluation.repaired_notebook_models import build_repaired_notebook_codecs
    repaired_methods, repaired_provenance = build_repaired_notebook_codecs(
        REPAIRED_EXPERIMENT_ROOT, PROJECT_ROOT, snr_db=10.0, base_seed=SEED,
    )
    METHODS.extend(repaired_methods)
    display(pd.DataFrame([repaired_provenance]))
else:
    print('Set SEMCOM_EXPERIMENT_ROOT to add the repaired DeepJSCC/NTSCC methods.')

# Preferred: a repository EncDecInterface adapter that is already built/loaded.
# channel = AWGNChannel()
# snr_db, rate = 10.0, 96
# METHODS.append(EncDecCodec(
#     name='MySwinJSCC', adapter=my_adapter, device=DEVICE,
#     version='checkpoint-sha256-prefix',
#     operating_point=f'rate={rate};snr_db={snr_db};snr=Es/N0',
#     encode_options={'rate': rate, 'snr_db': snr_db},
#     transport_fn=lambda latent: channel.transmit(latent, snr_db),
# ))

# Generic PyTorch example. encode_fn/decode_fn are the only required hooks.
# my_model = load_my_model(...).to(DEVICE).eval()
# METHODS.append(CallableCodec(
#     name='MyModel', version='checkpoint-sha256-prefix',
#     operating_point='rate=example;snr_db=10', device=DEVICE,
#     encode_fn=lambda x: my_model.encoder(x),
#     decode_fn=lambda z: my_model.decoder(z),
#     channel_uses_fn=lambda z: math.ceil(z[0].numel() / 2),
#     modules=[my_model],
#     flops=None,  # Fill from your model's trusted profiler if available.
# ))

keys = [(method.name, method.operating_point) for method in METHODS]
assert len(keys) == len(set(keys)), 'Duplicate method/operating-point key'
pd.DataFrame(keys, columns=['method', 'operating_point'])

D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\timm\models\layers\__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torch\jit\_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torch\jit\_script.py:365: FutureWarning: `torch.jit.script_method` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4223.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Encoder  dim=256, input_resolution=(256, 256), depth=1
Encoder  dim=256, input_resolution=(128, 128), depth=1
Encoder  dim=256, input_resolution=(64, 64), depth=2
Encoder  dim=256, input_resolution=(32, 32), depth=4
Decoder  dim=256, input_resolution=(16, 16), depth=4
Decoder  dim=256, input_resolution=(32, 32), depth=2
Decoder  dim=256, input_resolution=(64, 64), depth=1
Decoder  dim=256, input_resolution=(128, 128), depth=1

CONFIG RATE tensor([ 16,  32,  48,  64,  80,  96, 102, 118, 134, 160, 186, 192, 208, 224,
        240, 256])

,experiment_root,deepjscc_checkpoint_sha256,ntscc_checkpoint_sha256,deepjscc_codebook_sha256,ntscc_codebook_sha256,deepjscc_calibration,ntscc_calibration,snr_db,snr_definition,base_seed
0,D:\\Deskt...,00b33bac630555d9a0d72a76d0fea9103cef9a38df0d55...,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,7924944c1201260256eea1b47bcd990d820f3586ef01a9...,e553e847e60e0371cf215cef5694ee82869b97b4babe23...,"CIFAR-10 training indices 0-7, resized to 128x128",CIFAR-10 training indices 0-499 only; cached K...,10.0,Es/N0_dB,42

               method                                    operating_point
0           RAW_RGB24                                 8_bits_per_channel
1                JPEG                           quality=20;subsampling=0
2                JPEG                           quality=30;subsampling=0
3                JPEG                           quality=40;subsampling=0
4                JPEG                           quality=50;subsampling=0
5                JPEG                           quality=60;subsampling=0
6                JPEG                           quality=70;subsampling=0
7                JPEG                           quality=80;subsampling=0
8                JPEG                           quality=90;subsampling=0
9            DeepJSCC  tile=128;snr_db=10;snr=Es/N0;seed_per_image=42...
10              NTSCC  quality=1;snr_db=10;snr=Es/N0;seed_per_image=4...
11  DeepJSCC codebook  K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_pe...
12     NTSCC codebook  rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...

### DeepJSCC example with the repository adapter

Uncomment and edit this example on the teammate machine that has the external source/checkpoint. Models that only accept tiles should wrap tiling inside their callable hooks; the benchmark will reject a final image whose size differs from the original.

In [5]:
# from EncDecPipeline.Models.DeepJSCC.adapter import DeepJSCCAdapter
# from EncDecPipeline.Models.DeepJSCC.channel_wrapper import DeepJSCCChannelWrapper
# DEEP_ROOT = Path(r'D:/path/to/Deep-JSCC-PyTorch')
# CHECKPOINT = DEEP_ROOT / 'out' / 'checkpoint.pth'
# deep = DeepJSCCAdapter(CHECKPOINT, DEEP_ROOT, c=19, device=DEVICE).build()
# awgn = DeepJSCCChannelWrapper()
# snr_db = 10.0
# METHODS.append(EncDecCodec(
#     'DeepJSCC', deep, device=DEVICE,
#     version=deep.parameter_summary()['checkpoint_sha256'],
#     operating_point=f'c=19;snr_db={snr_db};snr=Es/N0',
#     transport_fn=lambda latent: awgn.transmit(latent, snr_db),
# ))

## 4. Run every method on all 24 images

This can take time, especially LPIPS on CPU. GPU timing is synchronized. Memory columns report process RSS and CUDA peak allocation; parameter/storage columns report static model complexity. FLOPs remain empty unless the model owner supplies a trusted value.

In [6]:
all_rows = []
for method in METHODS:
    method_rows = benchmark_codec(
        method, KODAK_FILES, run_id=RUN_ID, contributor=CONTRIBUTOR,
        project_root=PROJECT_ROOT, timing_repetitions=TIMING_REPETITIONS,
        warmup_repetitions=WARMUP_REPETITIONS, compute_lpips=COMPUTE_LPIPS,
    )
    assert len(method_rows) == 24
    all_rows.extend(method_rows)

per_image_df = pd.DataFrame(all_rows)
counts = per_image_df.groupby(['method', 'operating_point'])['image_id'].nunique()
assert (counts == 24).all(), f'Incomplete method results:\n{counts[counts != 24]}'
display(per_image_df)

Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:207: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:222: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

RAW_RGB24 8_bits_per_channel kodim01: PSNR=inf dB, SSIM=1.00000, total=1.79 ms

RAW_RGB24 8_bits_per_channel kodim02: PSNR=inf dB, SSIM=1.00000, total=2.52 ms

RAW_RGB24 8_bits_per_channel kodim03: PSNR=inf dB, SSIM=1.00000, total=2.64 ms

RAW_RGB24 8_bits_per_channel kodim04: PSNR=inf dB, SSIM=1.00000, total=2.26 ms

RAW_RGB24 8_bits_per_channel kodim05: PSNR=inf dB, SSIM=1.00000, total=1.87 ms

RAW_RGB24 8_bits_per_channel kodim06: PSNR=inf dB, SSIM=1.00000, total=1.91 ms

RAW_RGB24 8_bits_per_channel kodim07: PSNR=inf dB, SSIM=1.00000, total=3.79 ms

RAW_RGB24 8_bits_per_channel kodim08: PSNR=inf dB, SSIM=1.00000, total=2.64 ms

RAW_RGB24 8_bits_per_channel kodim09: PSNR=inf dB, SSIM=1.00000, total=2.11 ms

RAW_RGB24 8_bits_per_channel kodim10: PSNR=inf dB, SSIM=1.00000, total=3.61 ms

RAW_RGB24 8_bits_per_channel kodim11: PSNR=inf dB, SSIM=1.00000, total=1.86 ms

RAW_RGB24 8_bits_per_channel kodim12: PSNR=inf dB, SSIM=1.00000, total=2.27 ms

RAW_RGB24 8_bits_per_channel kodim13: PSNR=inf dB, SSIM=1.00000, total=1.94 ms

RAW_RGB24 8_bits_per_channel kodim14: PSNR=inf dB, SSIM=1.00000, total=3.38 ms

RAW_RGB24 8_bits_per_channel kodim15: PSNR=inf dB, SSIM=1.00000, total=2.17 ms

RAW_RGB24 8_bits_per_channel kodim16: PSNR=inf dB, SSIM=1.00000, total=1.73 ms

RAW_RGB24 8_bits_per_channel kodim17: PSNR=inf dB, SSIM=1.00000, total=3.00 ms

RAW_RGB24 8_bits_per_channel kodim18: PSNR=inf dB, SSIM=1.00000, total=1.91 ms

RAW_RGB24 8_bits_per_channel kodim19: PSNR=inf dB, SSIM=1.00000, total=2.27 ms

RAW_RGB24 8_bits_per_channel kodim20: PSNR=inf dB, SSIM=1.00000, total=2.17 ms

RAW_RGB24 8_bits_per_channel kodim21: PSNR=inf dB, SSIM=1.00000, total=3.73 ms

RAW_RGB24 8_bits_per_channel kodim22: PSNR=inf dB, SSIM=1.00000, total=2.27 ms

RAW_RGB24 8_bits_per_channel kodim23: PSNR=inf dB, SSIM=1.00000, total=1.78 ms

RAW_RGB24 8_bits_per_channel kodim24: PSNR=inf dB, SSIM=1.00000, total=2.93 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:207: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:222: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=20;subsampling=0 kodim01: PSNR=27.081 dB, SSIM=0.80746, total=15.54 ms

JPEG quality=20;subsampling=0 kodim02: PSNR=30.807 dB, SSIM=0.77924, total=9.08 ms

JPEG quality=20;subsampling=0 kodim03: PSNR=31.996 dB, SSIM=0.85820, total=8.22 ms

JPEG quality=20;subsampling=0 kodim04: PSNR=30.954 dB, SSIM=0.81753, total=8.61 ms

JPEG quality=20;subsampling=0 kodim05: PSNR=26.735 dB, SSIM=0.84201, total=7.45 ms

JPEG quality=20;subsampling=0 kodim06: PSNR=28.257 dB, SSIM=0.82373, total=6.43 ms

JPEG quality=20;subsampling=0 kodim07: PSNR=31.299 dB, SSIM=0.89455, total=5.39 ms

JPEG quality=20;subsampling=0 kodim08: PSNR=26.262 dB, SSIM=0.84363, total=7.17 ms

JPEG quality=20;subsampling=0 kodim09: PSNR=31.694 dB, SSIM=0.86667, total=7.40 ms

JPEG quality=20;subsampling=0 kodim10: PSNR=31.303 dB, SSIM=0.85017, total=5.59 ms

JPEG quality=20;subsampling=0 kodim11: PSNR=29.023 dB, SSIM=0.81171, total=5.93 ms

JPEG quality=20;subsampling=0 kodim12: PSNR=31.690 dB, SSIM=0.83292, total=7.59 ms

JPEG quality=20;subsampling=0 kodim13: PSNR=24.785 dB, SSIM=0.77715, total=7.59 ms

JPEG quality=20;subsampling=0 kodim14: PSNR=28.147 dB, SSIM=0.80664, total=9.56 ms

JPEG quality=20;subsampling=0 kodim15: PSNR=30.773 dB, SSIM=0.82884, total=19.44 ms

JPEG quality=20;subsampling=0 kodim16: PSNR=30.573 dB, SSIM=0.82693, total=9.89 ms

JPEG quality=20;subsampling=0 kodim17: PSNR=30.785 dB, SSIM=0.85230, total=10.37 ms

JPEG quality=20;subsampling=0 kodim18: PSNR=27.648 dB, SSIM=0.81020, total=16.15 ms

JPEG quality=20;subsampling=0 kodim19: PSNR=29.521 dB, SSIM=0.82557, total=13.47 ms

JPEG quality=20;subsampling=0 kodim20: PSNR=30.943 dB, SSIM=0.86697, total=8.35 ms

JPEG quality=20;subsampling=0 kodim21: PSNR=28.787 dB, SSIM=0.85303, total=8.82 ms

JPEG quality=20;subsampling=0 kodim22: PSNR=29.377 dB, SSIM=0.79800, total=8.64 ms

JPEG quality=20;subsampling=0 kodim23: PSNR=32.591 dB, SSIM=0.86719, total=9.96 ms

JPEG quality=20;subsampling=0 kodim24: PSNR=27.229 dB, SSIM=0.82831, total=14.09 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=30;subsampling=0 kodim01: PSNR=28.373 dB, SSIM=0.85077, total=8.45 ms

JPEG quality=30;subsampling=0 kodim02: PSNR=32.185 dB, SSIM=0.82474, total=7.22 ms

JPEG quality=30;subsampling=0 kodim03: PSNR=33.495 dB, SSIM=0.89072, total=7.98 ms

JPEG quality=30;subsampling=0 kodim04: PSNR=32.373 dB, SSIM=0.85766, total=8.76 ms

JPEG quality=30;subsampling=0 kodim05: PSNR=28.190 dB, SSIM=0.88258, total=11.31 ms

JPEG quality=30;subsampling=0 kodim06: PSNR=29.606 dB, SSIM=0.86390, total=6.98 ms

JPEG quality=30;subsampling=0 kodim07: PSNR=32.836 dB, SSIM=0.91896, total=10.60 ms

JPEG quality=30;subsampling=0 kodim08: PSNR=27.808 dB, SSIM=0.87993, total=15.28 ms

JPEG quality=30;subsampling=0 kodim09: PSNR=33.163 dB, SSIM=0.89298, total=6.08 ms

JPEG quality=30;subsampling=0 kodim10: PSNR=32.804 dB, SSIM=0.88152, total=7.09 ms

JPEG quality=30;subsampling=0 kodim11: PSNR=30.310 dB, SSIM=0.85249, total=10.09 ms

JPEG quality=30;subsampling=0 kodim12: PSNR=33.190 dB, SSIM=0.86904, total=5.94 ms

JPEG quality=30;subsampling=0 kodim13: PSNR=26.017 dB, SSIM=0.82677, total=10.19 ms

JPEG quality=30;subsampling=0 kodim14: PSNR=29.489 dB, SSIM=0.85205, total=9.00 ms

JPEG quality=30;subsampling=0 kodim15: PSNR=32.143 dB, SSIM=0.86500, total=5.47 ms

JPEG quality=30;subsampling=0 kodim16: PSNR=31.929 dB, SSIM=0.86827, total=6.63 ms

JPEG quality=30;subsampling=0 kodim17: PSNR=32.159 dB, SSIM=0.88856, total=8.17 ms

JPEG quality=30;subsampling=0 kodim18: PSNR=28.948 dB, SSIM=0.84959, total=6.03 ms

JPEG quality=30;subsampling=0 kodim19: PSNR=30.907 dB, SSIM=0.86311, total=7.60 ms

JPEG quality=30;subsampling=0 kodim20: PSNR=32.305 dB, SSIM=0.89118, total=12.33 ms

JPEG quality=30;subsampling=0 kodim21: PSNR=30.079 dB, SSIM=0.88109, total=12.82 ms

JPEG quality=30;subsampling=0 kodim22: PSNR=30.688 dB, SSIM=0.84248, total=11.10 ms

JPEG quality=30;subsampling=0 kodim23: PSNR=34.237 dB, SSIM=0.89867, total=10.66 ms

JPEG quality=30;subsampling=0 kodim24: PSNR=28.594 dB, SSIM=0.86821, total=11.13 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=40;subsampling=0 kodim01: PSNR=29.297 dB, SSIM=0.87719, total=9.63 ms

JPEG quality=40;subsampling=0 kodim02: PSNR=33.001 dB, SSIM=0.85017, total=7.21 ms

JPEG quality=40;subsampling=0 kodim03: PSNR=34.457 dB, SSIM=0.90859, total=8.30 ms

JPEG quality=40;subsampling=0 kodim04: PSNR=33.302 dB, SSIM=0.88045, total=8.39 ms

JPEG quality=40;subsampling=0 kodim05: PSNR=29.257 dB, SSIM=0.90472, total=8.59 ms

JPEG quality=40;subsampling=0 kodim06: PSNR=30.602 dB, SSIM=0.88777, total=11.58 ms

JPEG quality=40;subsampling=0 kodim07: PSNR=33.920 dB, SSIM=0.93253, total=10.74 ms

JPEG quality=40;subsampling=0 kodim08: PSNR=28.884 dB, SSIM=0.89997, total=9.35 ms

JPEG quality=40;subsampling=0 kodim09: PSNR=34.238 dB, SSIM=0.90673, total=9.00 ms

JPEG quality=40;subsampling=0 kodim10: PSNR=33.859 dB, SSIM=0.89925, total=7.78 ms

JPEG quality=40;subsampling=0 kodim11: PSNR=31.300 dB, SSIM=0.87873, total=7.52 ms

JPEG quality=40;subsampling=0 kodim12: PSNR=34.275 dB, SSIM=0.89030, total=6.76 ms

JPEG quality=40;subsampling=0 kodim13: PSNR=26.948 dB, SSIM=0.85558, total=9.52 ms

JPEG quality=40;subsampling=0 kodim14: PSNR=30.421 dB, SSIM=0.87715, total=9.32 ms

JPEG quality=40;subsampling=0 kodim15: PSNR=33.041 dB, SSIM=0.88478, total=6.47 ms

JPEG quality=40;subsampling=0 kodim16: PSNR=32.849 dB, SSIM=0.89001, total=7.41 ms

JPEG quality=40;subsampling=0 kodim17: PSNR=33.181 dB, SSIM=0.90707, total=9.20 ms

JPEG quality=40;subsampling=0 kodim18: PSNR=29.911 dB, SSIM=0.87312, total=9.05 ms

JPEG quality=40;subsampling=0 kodim19: PSNR=31.870 dB, SSIM=0.88390, total=9.85 ms

JPEG quality=40;subsampling=0 kodim20: PSNR=33.237 dB, SSIM=0.90519, total=9.54 ms

JPEG quality=40;subsampling=0 kodim21: PSNR=30.989 dB, SSIM=0.89758, total=12.59 ms

JPEG quality=40;subsampling=0 kodim22: PSNR=31.563 dB, SSIM=0.86664, total=7.84 ms

JPEG quality=40;subsampling=0 kodim23: PSNR=35.306 dB, SSIM=0.91506, total=9.44 ms

JPEG quality=40;subsampling=0 kodim24: PSNR=29.595 dB, SSIM=0.89072, total=7.68 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=50;subsampling=0 kodim01: PSNR=30.051 dB, SSIM=0.89514, total=8.22 ms

JPEG quality=50;subsampling=0 kodim02: PSNR=33.691 dB, SSIM=0.86910, total=6.08 ms

JPEG quality=50;subsampling=0 kodim03: PSNR=35.275 dB, SSIM=0.92215, total=11.50 ms

JPEG quality=50;subsampling=0 kodim04: PSNR=34.039 dB, SSIM=0.89610, total=8.42 ms

JPEG quality=50;subsampling=0 kodim05: PSNR=30.142 dB, SSIM=0.91998, total=7.85 ms

JPEG quality=50;subsampling=0 kodim06: PSNR=31.396 dB, SSIM=0.90373, total=6.65 ms

JPEG quality=50;subsampling=0 kodim07: PSNR=34.797 dB, SSIM=0.94251, total=7.76 ms

JPEG quality=50;subsampling=0 kodim08: PSNR=29.774 dB, SSIM=0.91403, total=8.51 ms

JPEG quality=50;subsampling=0 kodim09: PSNR=35.021 dB, SSIM=0.91597, total=8.47 ms

JPEG quality=50;subsampling=0 kodim10: PSNR=34.652 dB, SSIM=0.91076, total=7.37 ms

JPEG quality=50;subsampling=0 kodim11: PSNR=32.097 dB, SSIM=0.89493, total=8.32 ms

JPEG quality=50;subsampling=0 kodim12: PSNR=35.110 dB, SSIM=0.90508, total=9.47 ms

JPEG quality=50;subsampling=0 kodim13: PSNR=27.773 dB, SSIM=0.87682, total=10.79 ms

JPEG quality=50;subsampling=0 kodim14: PSNR=31.186 dB, SSIM=0.89432, total=8.61 ms

JPEG quality=50;subsampling=0 kodim15: PSNR=33.817 dB, SSIM=0.89902, total=8.09 ms

JPEG quality=50;subsampling=0 kodim16: PSNR=33.651 dB, SSIM=0.90642, total=7.30 ms

JPEG quality=50;subsampling=0 kodim17: PSNR=33.967 dB, SSIM=0.91944, total=8.51 ms

JPEG quality=50;subsampling=0 kodim18: PSNR=30.728 dB, SSIM=0.88973, total=9.26 ms

JPEG quality=50;subsampling=0 kodim19: PSNR=32.642 dB, SSIM=0.89866, total=9.03 ms

JPEG quality=50;subsampling=0 kodim20: PSNR=33.966 dB, SSIM=0.91538, total=8.27 ms

JPEG quality=50;subsampling=0 kodim21: PSNR=31.739 dB, SSIM=0.90900, total=6.98 ms

JPEG quality=50;subsampling=0 kodim22: PSNR=32.303 dB, SSIM=0.88476, total=7.94 ms

JPEG quality=50;subsampling=0 kodim23: PSNR=36.152 dB, SSIM=0.92614, total=8.48 ms

JPEG quality=50;subsampling=0 kodim24: PSNR=30.439 dB, SSIM=0.90669, total=8.51 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=60;subsampling=0 kodim01: PSNR=30.828 dB, SSIM=0.91069, total=9.23 ms

JPEG quality=60;subsampling=0 kodim02: PSNR=34.425 dB, SSIM=0.88596, total=7.91 ms

JPEG quality=60;subsampling=0 kodim03: PSNR=36.046 dB, SSIM=0.93248, total=6.07 ms

JPEG quality=60;subsampling=0 kodim04: PSNR=34.727 dB, SSIM=0.90925, total=7.77 ms

JPEG quality=60;subsampling=0 kodim05: PSNR=31.057 dB, SSIM=0.93309, total=7.98 ms

JPEG quality=60;subsampling=0 kodim06: PSNR=32.243 dB, SSIM=0.91780, total=11.95 ms

JPEG quality=60;subsampling=0 kodim07: PSNR=35.599 dB, SSIM=0.94997, total=10.68 ms

JPEG quality=60;subsampling=0 kodim08: PSNR=30.669 dB, SSIM=0.92618, total=14.59 ms

JPEG quality=60;subsampling=0 kodim09: PSNR=35.711 dB, SSIM=0.92308, total=6.97 ms

JPEG quality=60;subsampling=0 kodim10: PSNR=35.441 dB, SSIM=0.92097, total=10.84 ms

JPEG quality=60;subsampling=0 kodim11: PSNR=32.900 dB, SSIM=0.91006, total=17.94 ms

JPEG quality=60;subsampling=0 kodim12: PSNR=35.805 dB, SSIM=0.91638, total=21.08 ms

JPEG quality=60;subsampling=0 kodim13: PSNR=28.668 dB, SSIM=0.89569, total=12.40 ms

JPEG quality=60;subsampling=0 kodim14: PSNR=31.960 dB, SSIM=0.90907, total=9.64 ms

JPEG quality=60;subsampling=0 kodim15: PSNR=34.560 dB, SSIM=0.91097, total=7.99 ms

JPEG quality=60;subsampling=0 kodim16: PSNR=34.393 dB, SSIM=0.91922, total=7.57 ms

JPEG quality=60;subsampling=0 kodim17: PSNR=34.695 dB, SSIM=0.92849, total=6.96 ms

JPEG quality=60;subsampling=0 kodim18: PSNR=31.540 dB, SSIM=0.90369, total=7.66 ms

JPEG quality=60;subsampling=0 kodim19: PSNR=33.387 dB, SSIM=0.91059, total=8.15 ms

JPEG quality=60;subsampling=0 kodim20: PSNR=34.711 dB, SSIM=0.92350, total=10.19 ms

JPEG quality=60;subsampling=0 kodim21: PSNR=32.512 dB, SSIM=0.91879, total=7.92 ms

JPEG quality=60;subsampling=0 kodim22: PSNR=33.040 dB, SSIM=0.89981, total=7.89 ms

JPEG quality=60;subsampling=0 kodim23: PSNR=36.935 dB, SSIM=0.93482, total=9.39 ms

JPEG quality=60;subsampling=0 kodim24: PSNR=31.304 dB, SSIM=0.92022, total=10.06 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=70;subsampling=0 kodim01: PSNR=31.945 dB, SSIM=0.92919, total=11.36 ms

JPEG quality=70;subsampling=0 kodim02: PSNR=35.374 dB, SSIM=0.90455, total=8.47 ms

JPEG quality=70;subsampling=0 kodim03: PSNR=37.084 dB, SSIM=0.94442, total=5.58 ms

JPEG quality=70;subsampling=0 kodim04: PSNR=35.636 dB, SSIM=0.92375, total=8.35 ms

JPEG quality=70;subsampling=0 kodim05: PSNR=32.326 dB, SSIM=0.94755, total=10.50 ms

JPEG quality=70;subsampling=0 kodim06: PSNR=33.433 dB, SSIM=0.93361, total=6.97 ms

JPEG quality=70;subsampling=0 kodim07: PSNR=36.714 dB, SSIM=0.95855, total=6.20 ms

JPEG quality=70;subsampling=0 kodim08: PSNR=31.922 dB, SSIM=0.94004, total=9.57 ms

JPEG quality=70;subsampling=0 kodim09: PSNR=36.733 dB, SSIM=0.93233, total=7.13 ms

JPEG quality=70;subsampling=0 kodim10: PSNR=36.480 dB, SSIM=0.93226, total=5.80 ms

JPEG quality=70;subsampling=0 kodim11: PSNR=34.058 dB, SSIM=0.92692, total=11.07 ms

JPEG quality=70;subsampling=0 kodim12: PSNR=36.778 dB, SSIM=0.92972, total=6.77 ms

JPEG quality=70;subsampling=0 kodim13: PSNR=29.959 dB, SSIM=0.91785, total=11.00 ms

JPEG quality=70;subsampling=0 kodim14: PSNR=33.026 dB, SSIM=0.92615, total=9.25 ms

JPEG quality=70;subsampling=0 kodim15: PSNR=35.595 dB, SSIM=0.92526, total=10.18 ms

JPEG quality=70;subsampling=0 kodim16: PSNR=35.466 dB, SSIM=0.93416, total=9.43 ms

JPEG quality=70;subsampling=0 kodim17: PSNR=35.743 dB, SSIM=0.94018, total=6.87 ms

JPEG quality=70;subsampling=0 kodim18: PSNR=32.688 dB, SSIM=0.92050, total=11.85 ms

JPEG quality=70;subsampling=0 kodim19: PSNR=34.387 dB, SSIM=0.92504, total=9.22 ms

JPEG quality=70;subsampling=0 kodim20: PSNR=35.696 dB, SSIM=0.93384, total=12.48 ms

JPEG quality=70;subsampling=0 kodim21: PSNR=33.594 dB, SSIM=0.93049, total=9.21 ms

JPEG quality=70;subsampling=0 kodim22: PSNR=34.029 dB, SSIM=0.91698, total=9.17 ms

JPEG quality=70;subsampling=0 kodim23: PSNR=37.911 dB, SSIM=0.94410, total=7.89 ms

JPEG quality=70;subsampling=0 kodim24: PSNR=32.495 dB, SSIM=0.93559, total=12.02 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=80;subsampling=0 kodim01: PSNR=33.712 dB, SSIM=0.95025, total=9.74 ms

JPEG quality=80;subsampling=0 kodim02: PSNR=36.718 dB, SSIM=0.92627, total=7.39 ms

JPEG quality=80;subsampling=0 kodim03: PSNR=38.586 dB, SSIM=0.95720, total=11.33 ms

JPEG quality=80;subsampling=0 kodim04: PSNR=37.016 dB, SSIM=0.94076, total=8.94 ms

JPEG quality=80;subsampling=0 kodim05: PSNR=34.226 dB, SSIM=0.96334, total=8.37 ms

JPEG quality=80;subsampling=0 kodim06: PSNR=35.186 dB, SSIM=0.95091, total=13.49 ms

JPEG quality=80;subsampling=0 kodim07: PSNR=38.284 dB, SSIM=0.96746, total=8.13 ms

JPEG quality=80;subsampling=0 kodim08: PSNR=33.760 dB, SSIM=0.95584, total=15.01 ms

JPEG quality=80;subsampling=0 kodim09: PSNR=38.114 dB, SSIM=0.94296, total=8.12 ms

JPEG quality=80;subsampling=0 kodim10: PSNR=37.923 dB, SSIM=0.94528, total=8.83 ms

JPEG quality=80;subsampling=0 kodim11: PSNR=35.750 dB, SSIM=0.94520, total=7.44 ms

JPEG quality=80;subsampling=0 kodim12: PSNR=38.148 dB, SSIM=0.94426, total=8.32 ms

JPEG quality=80;subsampling=0 kodim13: PSNR=32.023 dB, SSIM=0.94420, total=9.03 ms

JPEG quality=80;subsampling=0 kodim14: PSNR=34.620 dB, SSIM=0.94553, total=8.15 ms

JPEG quality=80;subsampling=0 kodim15: PSNR=37.052 dB, SSIM=0.94134, total=11.48 ms

JPEG quality=80;subsampling=0 kodim16: PSNR=36.977 dB, SSIM=0.95019, total=7.20 ms

JPEG quality=80;subsampling=0 kodim17: PSNR=37.215 dB, SSIM=0.95228, total=11.69 ms

JPEG quality=80;subsampling=0 kodim18: PSNR=34.425 dB, SSIM=0.93958, total=9.26 ms

JPEG quality=80;subsampling=0 kodim19: PSNR=35.888 dB, SSIM=0.94222, total=8.30 ms

JPEG quality=80;subsampling=0 kodim20: PSNR=37.169 dB, SSIM=0.94653, total=6.24 ms

JPEG quality=80;subsampling=0 kodim21: PSNR=35.287 dB, SSIM=0.94464, total=12.49 ms

JPEG quality=80;subsampling=0 kodim22: PSNR=35.543 dB, SSIM=0.93670, total=9.63 ms

JPEG quality=80;subsampling=0 kodim23: PSNR=39.282 dB, SSIM=0.95460, total=7.81 ms

JPEG quality=80;subsampling=0 kodim24: PSNR=34.301 dB, SSIM=0.95303, total=8.99 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

JPEG quality=90;subsampling=0 kodim01: PSNR=37.464 dB, SSIM=0.97602, total=11.64 ms

JPEG quality=90;subsampling=0 kodim02: PSNR=39.358 dB, SSIM=0.95489, total=10.00 ms

JPEG quality=90;subsampling=0 kodim03: PSNR=41.283 dB, SSIM=0.97227, total=7.52 ms

JPEG quality=90;subsampling=0 kodim04: PSNR=39.673 dB, SSIM=0.96336, total=9.41 ms

JPEG quality=90;subsampling=0 kodim05: PSNR=37.783 dB, SSIM=0.98120, total=10.92 ms

JPEG quality=90;subsampling=0 kodim06: PSNR=38.547 dB, SSIM=0.97211, total=10.16 ms

JPEG quality=90;subsampling=0 kodim07: PSNR=41.080 dB, SSIM=0.97830, total=12.18 ms

JPEG quality=90;subsampling=0 kodim08: PSNR=37.267 dB, SSIM=0.97620, total=9.48 ms

JPEG quality=90;subsampling=0 kodim09: PSNR=40.510 dB, SSIM=0.95822, total=10.53 ms

JPEG quality=90;subsampling=0 kodim10: PSNR=40.427 dB, SSIM=0.96284, total=8.38 ms

JPEG quality=90;subsampling=0 kodim11: PSNR=38.988 dB, SSIM=0.96901, total=10.47 ms

JPEG quality=90;subsampling=0 kodim12: PSNR=40.624 dB, SSIM=0.96391, total=10.84 ms

JPEG quality=90;subsampling=0 kodim13: PSNR=36.159 dB, SSIM=0.97544, total=12.74 ms

JPEG quality=90;subsampling=0 kodim14: PSNR=37.842 dB, SSIM=0.97043, total=9.92 ms

JPEG quality=90;subsampling=0 kodim15: PSNR=39.782 dB, SSIM=0.96247, total=9.56 ms

JPEG quality=90;subsampling=0 kodim16: PSNR=39.928 dB, SSIM=0.97055, total=15.51 ms

JPEG quality=90;subsampling=0 kodim17: PSNR=39.979 dB, SSIM=0.96872, total=9.19 ms

JPEG quality=90;subsampling=0 kodim18: PSNR=37.707 dB, SSIM=0.96427, total=22.10 ms

JPEG quality=90;subsampling=0 kodim19: PSNR=38.912 dB, SSIM=0.96545, total=11.17 ms

JPEG quality=90;subsampling=0 kodim20: PSNR=40.002 dB, SSIM=0.96420, total=8.75 ms

JPEG quality=90;subsampling=0 kodim21: PSNR=38.594 dB, SSIM=0.96356, total=12.48 ms

JPEG quality=90;subsampling=0 kodim22: PSNR=38.549 dB, SSIM=0.96260, total=9.96 ms

JPEG quality=90;subsampling=0 kodim23: PSNR=41.508 dB, SSIM=0.96745, total=6.97 ms

JPEG quality=90;subsampling=0 kodim24: PSNR=37.814 dB, SSIM=0.97436, total=13.22 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim01: PSNR=15.701 dB, SSIM=0.31072, total=249.67 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim02: PSNR=17.299 dB, SSIM=0.17376, total=196.39 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim03: PSNR=16.282 dB, SSIM=0.14149, total=182.12 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim04: PSNR=16.255 dB, SSIM=0.16457, total=178.24 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim05: PSNR=16.561 dB, SSIM=0.37310, total=196.24 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim06: PSNR=16.272 dB, SSIM=0.26158, total=186.89 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim07: PSNR=15.933 dB, SSIM=0.21655, total=198.16 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim08: PSNR=16.005 dB, SSIM=0.41128, total=205.12 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim09: PSNR=15.674 dB, SSIM=0.14831, total=189.60 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim10: PSNR=15.632 dB, SSIM=0.14938, total=225.67 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim11: PSNR=16.230 dB, SSIM=0.22293, total=200.45 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim12: PSNR=16.135 dB, SSIM=0.14857, total=213.34 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim13: PSNR=15.976 dB, SSIM=0.34976, total=1283.35 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim14: PSNR=16.538 dB, SSIM=0.26612, total=348.73 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim15: PSNR=17.934 dB, SSIM=0.23783, total=262.66 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim16: PSNR=16.047 dB, SSIM=0.15658, total=238.57 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim17: PSNR=17.056 dB, SSIM=0.22527, total=181.44 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim18: PSNR=17.060 dB, SSIM=0.27662, total=228.70 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim19: PSNR=16.020 dB, SSIM=0.21968, total=168.63 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim20: PSNR=19.197 dB, SSIM=0.43472, total=218.26 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim21: PSNR=15.867 dB, SSIM=0.22061, total=177.26 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim22: PSNR=16.013 dB, SSIM=0.17737, total=189.36 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim23: PSNR=16.567 dB, SSIM=0.14823, total=254.98 ms

DeepJSCC tile=128;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim24: PSNR=16.190 dB, SSIM=0.26283, total=202.65 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim01: PSNR=26.569 dB, SSIM=0.75635, total=10465.90 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim02: PSNR=31.533 dB, SSIM=0.80046, total=9454.37 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim03: PSNR=33.282 dB, SSIM=0.89050, total=9827.06 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim04: PSNR=31.361 dB, SSIM=0.82991, total=10976.57 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim05: PSNR=26.319 dB, SSIM=0.81614, total=10991.87 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim06: PSNR=28.033 dB, SSIM=0.80142, total=9565.36 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim07: PSNR=32.120 dB, SSIM=0.92199, total=11271.99 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim08: PSNR=25.748 dB, SSIM=0.82196, total=10839.17 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim09: PSNR=32.607 dB, SSIM=0.89484, total=10654.99 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim10: PSNR=32.589 dB, SSIM=0.88701, total=10611.78 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim11: PSNR=29.118 dB, SSIM=0.80811, total=9708.98 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim12: PSNR=32.908 dB, SSIM=0.85621, total=9501.21 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim13: PSNR=23.832 dB, SSIM=0.68808, total=9635.72 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim14: PSNR=27.834 dB, SSIM=0.78595, total=9634.45 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim15: PSNR=31.376 dB, SSIM=0.85017, total=10590.07 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim16: PSNR=30.966 dB, SSIM=0.83159, total=9808.20 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim17: PSNR=31.512 dB, SSIM=0.88043, total=10006.95 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim18: PSNR=26.974 dB, SSIM=0.78513, total=10403.61 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim19: PSNR=30.068 dB, SSIM=0.82689, total=9458.37 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim20: PSNR=31.852 dB, SSIM=0.87388, total=9250.41 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim21: PSNR=28.429 dB, SSIM=0.84792, total=11379.59 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim22: PSNR=29.442 dB, SSIM=0.78399, total=9807.07 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim23: PSNR=33.757 dB, SSIM=0.91146, total=10157.12 ms

NTSCC quality=1;snr_db=10;snr=Es/N0;seed_per_image=42+index kodim24: PSNR=26.749 dB, SSIM=0.81878, total=10559.73 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim01: PSNR=19.678 dB, SSIM=0.38355, total=4350.27 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim02: PSNR=21.103 dB, SSIM=0.44719, total=4103.82 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim03: PSNR=21.051 dB, SSIM=0.45596, total=6219.00 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim04: PSNR=21.130 dB, SSIM=0.44079, total=2620.94 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim05: PSNR=18.930 dB, SSIM=0.40164, total=2686.04 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim06: PSNR=19.978 dB, SSIM=0.42825, total=3677.37 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim07: PSNR=21.022 dB, SSIM=0.42551, total=2425.88 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim08: PSNR=17.215 dB, SSIM=0.39351, total=2963.02 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim09: PSNR=20.736 dB, SSIM=0.41303, total=2587.78 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim10: PSNR=21.349 dB, SSIM=0.41667, total=2739.69 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim11: PSNR=20.900 dB, SSIM=0.40307, total=2822.41 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim12: PSNR=21.082 dB, SSIM=0.46198, total=2376.23 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim13: PSNR=18.715 dB, SSIM=0.36470, total=2385.60 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim14: PSNR=19.784 dB, SSIM=0.41088, total=2606.87 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim15: PSNR=19.785 dB, SSIM=0.50261, total=2514.89 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim16: PSNR=21.922 dB, SSIM=0.39742, total=2409.85 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim17: PSNR=21.926 dB, SSIM=0.49963, total=2462.21 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim18: PSNR=20.662 dB, SSIM=0.42445, total=2406.98 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim19: PSNR=20.136 dB, SSIM=0.39339, total=2595.16 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim20: PSNR=19.835 dB, SSIM=0.62213, total=2532.38 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim21: PSNR=20.165 dB, SSIM=0.42532, total=2476.34 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim22: PSNR=21.440 dB, SSIM=0.41508, total=2388.33 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim23: PSNR=19.979 dB, SSIM=0.48984, total=2574.30 ms

DeepJSCC codebook K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim24: PSNR=20.264 dB, SSIM=0.43377, total=2542.45 ms
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]

D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:207: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\torchvision\models\_utils.py:222: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Loading model from: D:\<local OneDrive>\Desktop\image_semcom\.venv\Lib\site-packages\lpips\weights\v0.1\alex.pth

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim01: PSNR=25.502 dB, SSIM=0.72209, total=15590.68 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim02: PSNR=30.116 dB, SSIM=0.78658, total=25692.16 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim03: PSNR=31.042 dB, SSIM=0.87392, total=23046.05 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim04: PSNR=29.673 dB, SSIM=0.81394, total=28621.95 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim05: PSNR=22.185 dB, SSIM=0.73269, total=25955.07 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim06: PSNR=26.368 dB, SSIM=0.76430, total=21251.02 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim07: PSNR=29.630 dB, SSIM=0.90146, total=16419.15 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim08: PSNR=20.835 dB, SSIM=0.72919, total=25740.70 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim09: PSNR=29.220 dB, SSIM=0.87610, total=14199.13 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim10: PSNR=29.872 dB, SSIM=0.86915, total=13425.81 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim11: PSNR=26.774 dB, SSIM=0.77616, total=13413.10 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim12: PSNR=30.153 dB, SSIM=0.83927, total=13856.20 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim13: PSNR=21.509 dB, SSIM=0.60433, total=19542.13 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim14: PSNR=24.960 dB, SSIM=0.74104, total=15092.16 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim15: PSNR=29.761 dB, SSIM=0.83510, total=14254.38 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim16: PSNR=30.317 dB, SSIM=0.81465, total=14533.75 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim17: PSNR=29.100 dB, SSIM=0.85876, total=13786.34 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim18: PSNR=24.690 dB, SSIM=0.74488, total=14910.34 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim19: PSNR=26.617 dB, SSIM=0.79478, total=13966.75 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim20: PSNR=28.970 dB, SSIM=0.85289, total=14873.20 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim21: PSNR=25.434 dB, SSIM=0.80687, total=14597.46 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim22: PSNR=27.577 dB, SSIM=0.75991, total=13984.44 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim23: PSNR=28.944 dB, SSIM=0.89193, total=13856.68 ms

NTSCC codebook rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;snr_db=10;seed_per_image=42+index kodim24: PSNR=23.207 dB, SSIM=0.77114, total=15024.99 ms

,schema_version,run_id,timestamp_utc,contributor,git_commit,method,method_version,operating_point,device,image_id,...,peak_gpu_allocated_mb,model_parameters,trainable_parameters,model_size_mb,flops,psnr_db,ssim,lpips,timing_repetitions,notes
0,1.0,repaired-kodak24-20260922,2026-09-22T10:45:14.309537+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,RAW_RGB24,RGB24,8_bits_per_channel,cpu,kodim01,...,None,0,0,0.0000,None,inf,1.000000,0.000000,1,
1,1.0,repaired-kodak24-20260922,2026-09-22T10:45:14.778548+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,RAW_RGB24,RGB24,8_bits_per_channel,cpu,kodim02,...,None,0,0,0.0000,None,inf,1.000000,0.000000,1,
2,1.0,repaired-kodak24-20260922,2026-09-22T10:45:15.150891+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,RAW_RGB24,RGB24,8_bits_per_channel,cpu,kodim03,...,None,0,0,0.0000,None,inf,1.000000,0.000000,1,
3,1.0,repaired-kodak24-20260922,2026-09-22T10:45:15.517386+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,RAW_RGB24,RGB24,8_bits_per_channel,cpu,kodim04,...,None,0,0,0.0000,None,inf,1.000000,0.000000,1,
4,1.0,repaired-kodak24-20260922,2026-09-22T10:45:15.884752+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,RAW_RGB24,RGB24,8_bits_per_channel,cpu,kodim05,...,None,0,0,0.0000,None,inf,1.000000,0.000000,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,1.0,repaired-kodak24-20260922,2026-09-22T10:59:00.673608+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,NTSCC codebook,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,cpu,kodim20,...,None,31358531,0,131.6437,None,28.969515,0.852892,0.182240,1,Rate-conditioned PQ4 K=256 design from the rep...
308,1.0,repaired-kodak24-20260922,2026-09-22T10:59:15.695584+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,NTSCC codebook,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,cpu,kodim21,...,None,31358531,0,131.6437,None,25.433521,0.806867,0.287019,1,Rate-conditioned PQ4 K=256 design from the rep...
309,1.0,repaired-kodak24-20260922,2026-09-22T10:59:30.144715+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,NTSCC codebook,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,cpu,kodim22,...,None,31358531,0,131.6437,None,27.576715,0.759908,0.319514,1,Rate-conditioned PQ4 K=256 design from the rep...
310,1.0,repaired-kodak24-20260922,2026-09-22T10:59:44.453558+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,NTSCC codebook,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,cpu,kodim23,...,None,31358531,0,131.6437,None,28.944324,0.891930,0.165984,1,Rate-conditioned PQ4 K=256 design from the rep...
311,1.0,repaired-kodak24-20260922,2026-09-22T10:59:59.901949+00:00,Nandini.P,71b5501bd21988c98a482301e9d9129768b33738,NTSCC codebook,7a8d1990dbd678ea5d3daa02c3aeaaf4459b347a96d6aa...,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,cpu,kodim24,...,None,31358531,0,131.6437,None,23.207109,0.771139,0.259281,1,Rate-conditioned PQ4 K=256 design from the rep...

In [7]:
summary_df = pd.DataFrame(summarize_rows(all_rows))
columns = [
    'method', 'operating_point', 'images', 'compression_ratio_mean',
    'bits_per_pixel_mean', 'cbr_mean', 'encode_time_ms_mean',
    'decode_time_ms_mean', 'cpu_process_time_ms_mean',
    'peak_cpu_rss_delta_mb_mean', 'peak_gpu_allocated_mb_mean',
    'model_parameters_mean', 'model_size_mb_mean', 'flops_mean',
    'psnr_db_mean', 'ssim_mean', 'lpips_mean',
]
display(summary_df[columns].sort_values(['method', 'operating_point']))

,method,operating_point,images,compression_ratio_mean,bits_per_pixel_mean,cbr_mean,encode_time_ms_mean,decode_time_ms_mean,cpu_process_time_ms_mean,peak_cpu_rss_delta_mb_mean,peak_gpu_allocated_mb_mean,model_parameters_mean,model_size_mb_mean,flops_mean,psnr_db_mean,ssim_mean,lpips_mean
0,DeepJSCC,tile=128;snr_db=10;snr=Es/N0;seed_per_image=42...,24,NaN,NaN,0.162547,82.529421,174.824954,834.635417,1.169108,None,167212.0,0.637863,None,16.435117,0.237411,0.957790
1,DeepJSCC codebook,K=256;tile=128;ldpc=1/2;qpsk;snr_db=10;seed_pe...,24,58.386854,0.411051,0.137153,234.986933,2659.504746,10281.250000,35.585449,None,167212.0,0.656418,None,20.366174,0.435433,0.651415
2,JPEG,quality=20;subsampling=0,24,41.024034,0.618022,NaN,4.587112,5.026638,49.479167,0.519531,None,0.0,0.000000,None,29.510833,0.832039,0.171837
3,JPEG,quality=30;subsampling=0,24,32.544840,0.784262,NaN,4.036638,5.001208,38.411458,0.138835,None,0.0,0.000000,None,30.909509,0.869178,0.115830
4,JPEG,quality=40;subsampling=0,24,27.679328,0.925119,NaN,4.048617,4.816883,35.807292,0.891602,None,0.0,0.000000,None,31.887646,0.890134,0.087657
5,JPEG,quality=50;subsampling=0,24,24.171917,1.061386,NaN,3.682542,4.667483,34.505208,0.340007,None,0.0,0.000000,None,32.683744,0.904827,0.069817
6,JPEG,quality=60;subsampling=0,24,21.174493,1.213189,NaN,4.297313,5.654283,41.666667,0.291829,None,0.0,0.000000,None,33.464933,0.917117,0.056440
7,JPEG,quality=70;subsampling=0,24,17.747891,1.447334,NaN,4.013325,5.000938,35.156250,0.907878,None,0.0,0.000000,None,34.544633,0.931377,0.041121
8,JPEG,quality=80;subsampling=0,24,13.886195,1.846283,NaN,4.004471,5.387158,42.968750,0.423014,None,0.0,0.000000,None,36.133526,0.947524,0.024683
9,JPEG,quality=90;subsampling=0,24,9.072809,2.799021,NaN,4.608546,6.354604,44.270833,0.330729,None,0.0,0.000000,None,39.157348,0.968242,0.008078
10,NTSCC,quality=1;snr_db=10;snr=Es/N0;seed_per_image=4...,24,NaN,NaN,0.023976,6692.276450,3497.746663,38041.015625,1570.820964,None,31358531.0,126.498695,None,29.790670,0.832049,0.222139
11,NTSCC codebook,rc_pq4_k256_raw;cifar500_only;ldpc=1/2;qpsk;sn...,24,79.972975,0.304067,0.101888,11345.396154,5972.673038,48971.354167,1569.364909,None,31358531.0,131.643700,None,27.185590,0.798380,0.249833
12,RAW_RGB24,8_bits_per_channel,24,1.000000,24.000000,NaN,1.529162,0.910288,11.067708,0.144857,None,0.0,0.000000,None,inf,1.000000,0.000000

## 5. Append to the shared CSV

Review the tables first. Then set the switch to `True` and run once. The writer is schema-checked, locked, atomic, and idempotent for the same run/method/operating-point/image key. Pull/rebase main before running and again before pushing, because Git itself can still report a CSV merge conflict.

In [8]:
APPEND_RESULTS = os.getenv('KODAK_BENCHMARK_APPEND', '0') == '1'
if APPEND_RESULTS:
    added = append_rows_csv(CSV_PATH, all_rows)
    print(f'Appended {added} new rows to {CSV_PATH}')
else:
    print('Review complete? Set APPEND_RESULTS=True to persist these rows.')

Appended 312 new rows to D:\<local OneDrive>\Desktop\image_semcom\references\SemanticSchedulerEnd2End_team\results\kodak24_benchmark.csv

## Interpretation checklist

- Compare quality at matched rate/resource points, not only the highest PSNR.
- RAW must be lossless (`PSNR=∞`, `SSIM=1`, `LPIPS≈0`, compression ratio `1`).
- JPEG has payload bits/BPP/compression ratio but no CBR without an explicit modulation/coding chain.
- Analog JSCC normally has channel uses/CBR but no payload bits.
- Do not compare CPU and GPU latency as if they were the same hardware condition; use the `device`, version, commit, and contributor columns.
- A publishable stochastic-channel result should repeat multiple seeded trials. Use a separate run ID per trial or put the trial seed in the operating point.